import { StyleSheet, Dimensions } from "react-native";
import Constants from "expo-constants";

import { colors, fonts } from "../../Styles";
const { width } = Dimensions.get("window");

const Styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: Constants.statusBarHeight,
  },
  input: {
    height: 54,
    width: "100%",
    backgroundColor: colors.white,
    justifyContent: "center",
    paddingHorizontal: 16,
    marginRight: 10,
    fontFamily: "Archivo_700Bold",
    fontSize: 14,
  },
  contentInput: {
    position: "relative",
    backgroundColor: colors.white,
  },
  indicator: {
    position: "absolute",
    zIndex: 1,
    right: 15,
    top: 20,
  },
  containerProduct: {
    position: "relative",
    backgroundColor: "#E6E6E6",
    padding: 10,
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 10,
    marginTop: 5,
  },
  product: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  textPromotion: {
    position: "absolute",
    borderRadius: 8,
    padding: 5,
    backgroundColor: colors.red,
    color: colors.white,
    fontSize: 8,
    left: -18,
    top: 32,
    transform: [{ rotate: "-90deg" }],
    zIndex: 1,
  },
  imgProduct: {
    height: 60,
    width: 60,
    borderRadius: 30,
    marginRight: 10,
  },
  groupButton: {
    position: "relative",
    alignItems: "flex-end",
  },
  button: {
    position: "absolute",
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    bottom: 0,
    right: 20,
  },
  textAmount: {
    fontFamily: "Archivo_700Bold",
    width: 40,
    textAlign: "center",
    fontSize: 24,
    marginHorizontal: 10,
  },
  description: {
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.regular,
  },
  price: {
    fontFamily: "Poppins_600SemiBold",
    fontSize: fonts.small,
    color: colors.regular,
    marginTop: 5,
  },
  total: {
    textAlign: "right",
    paddingRight: 5,
    fontFamily: "Poppins_600SemiBold",
    fontSize: fonts.big,
    color: colors.darker,
    width: "35%",
    borderLeftWidth: 2,
    borderLeftColor: colors.light,
  },
  textLineBlock: {
    position: "relative",
    justifyContent: "space-between",
    flexDirection: "row",
    // alignItems: "center",
    width: "80%",
    height: "100%",
  },
  block: {
    flex: 1,
    flexDirection: "column",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    margin: 8,
    width: "100%",
    height: "100%",
    backgroundColor: colors.white,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  headerImage: {
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    height: 200,
    width: width,
  },
  close: {
    position: "absolute",
    top: 10,
    right: 10,
    height: 40,
    width: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  imageModal: {
    marginTop: 10,
    width: width / 1.9,
    height: width / 1.9,
    resizeMode: "center",
  },
  modalImageBG: {
    position: "absolute",
    width: "75%",
    height: 55,
    resizeMode: "contain",
  },
  imageModalLeft: {
    position: "absolute",
    left: 15,
    top: -20,
    width: 150,
  },
  titleoffsetScrollY: {
    position: "absolute",
    top: 70,
    width: width - 160,
    right: 10,
    alignItems: "center",
  },
  modalTitleOfficeScrollY: {
    textAlign: "center",
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.big,
    color: colors.darker,
    marginBottom: 10,
  },
  modalDescription: {
    width: width,
    padding: 10,
  },
  modalTitleDescription: {
    marginTop: -10,
    marginBottom: 10,
    fontFamily: "Archivo_700Bold",
    color: colors.regular,
    fontSize: fonts.bigger,
    paddingLeft: 15,
    textAlign: "center",
    textTransform: "uppercase",
  },
  modalTextDescription: {
    fontFamily: "Poppins_400Regular",
    color: colors.regular,
    fontSize: fonts.smaller,
    paddingHorizontal: 28,
    textAlign: "justify",
  },
  modalContentAmount: {
    alignItems: "center",
    justifyContent: "space-around",
    flexDirection: "row",
    width: width,
    paddingVertical: 10,
    marginBottom: 10,
  },
  modalControlAmount: {
    flexDirection: "row",
  },
  modalBtnSub: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.light,
    height: 43,
    width: 43,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
  },
  modalBtnAdd: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.light,
    height: 43,
    width: 43,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  modalAmount: {
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.big,
    backgroundColor: colors.light,
    height: 43,
    minWidth: 43,
    maxWidth: 100,
    marginHorizontal: 1,
    textAlignVertical: "center",
    textAlign: "center",
  },
  modalPrice: {
    width: "100%",
  },
  modalPriceNormal: {
    textAlign: "right",
    paddingRight: 15,
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.bigger,
    color: colors.darker,
  },
  modalTextPrice: {
    top: 8,
    textAlign: "right",
    paddingRight: 15,
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.small,
    color: colors.darker,
    zIndex: 1,
  },
  modalTextPricePromotion: {
    textAlign: "right",
    paddingRight: 15,
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.bigger,
    color: colors.red,
  },
  contentAdditional: {
    backgroundColor: colors.lighter,
    width: width,
    paddingHorizontal: 20,
    paddingVertical: 5,
    borderBottomLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  modalTitleAdditional: {
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.big,
  },
  modalContentButton: {
    alignItems: "center",
    height: 100,
    padding: 20,
    marginBottom: 8,
  },
  textModalProduct: {
    fontSize: fonts.bigger,
  },
  textInformedAmount: {
    fontFamily: "Archivo_700Bold",
    fontSize: 16,
    textAlign: "center",
    marginBottom: 10,
  },
  textModalProduct: {
    fontSize: fonts.bigger,
  },
  groupText: {
    flexDirection: "row",
    alignItems: "center",
  },
  textValuePromotion: {
    fontSize: fonts.big,
    fontWeight: "bold",
    color: colors.red,
  },
  groupAmount: {
    flexDirection: "row",
    paddingVertical: 15,
    alignItems: "center",
  },
  textAmout: {
    fontSize: 35,
    paddingHorizontal: 45,
  },
  textAlertProductCarts: {
    fontFamily: "Archivo_400Regular",
    fontSize: 16,
    paddingBottom: 20,
    color: colors.red,
    textAlign: "center",
    lineHeight: 20,
  },
  textAlert: {
    fontFamily: "Poppins_400Regular",
    fontSize: 12,
    textAlign: "center",
    color: colors.darker,
  },
  containerButtonAdd: {
    flexDirection: "row",
    justifyContent: "space-around",
    borderTopWidth: 2,
    borderTopColor: colors.lighter,
    width: "100%",
  },
  buttonComprar: {
    flexDirection: "row",
    backgroundColor: colors.primary,
    height: 50,
    width: "90%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  titleButtonComprar: {
    fontFamily: "Archivo_700Bold",
    color: colors.darker,
  },
  buttonCancel: {
    backgroundColor: colors.light,
    height: 50,
    width: 130,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  titleButtonCancel: {
    fontFamily: "Archivo_700Bold",
    color: colors.darker,
  },

  buy: {
    opacity: 0.3,
  },
  textUnit: {
    position: "absolute",
    color: colors.red,
    padding: 2,
    left: 5,
    top: 5,
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.small,
    zIndex: 1,
  },
  imgContent: {
    backgroundColor: colors.primary,
    height: "50%",
  },
  titleDescription: {
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.smaller,
    color: colors.dark,
    textAlign: "center",
    textTransform: "uppercase",
  },
  priceContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 5,
    paddingLeft: 10,
    height: "25%",
  },
  imgProductPromotion: {
    position: "absolute",
    top: 0,
    left: -5,
    width: 160,
    height: 90,
    resizeMode: "contain",
    zIndex: 1,
  },
  textPrice: {
    fontFamily: "Archivo_700Bold",
  },
});

export default Styles;
