import { StyleSheet, Dimensions } from "react-native";
import { colors, fonts } from "../../Styles";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    position: "relative",
    backgroundColor: colors.white,
    overflow: "hidden",
  },
  centeredView: {
    justifyContent: "center",
    alignItems: "center",
  },
  contentImage: {
    position: "relative",
    alignItems: "center",
    width: "100%",
    height: 200,
  },
  imageModal: {
    width: "100%",
    height: 200,
  },
  modalView: {
    margin: 8,
    width: "100%",
    height: "100%",
    backgroundColor: colors.white,
    alignItems: "center",
  },
  headerImage: {
    position: "absolute",
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    height: 80,
    width: width,
  },
  close: {
    position: "absolute",
    top: 0,
    right: 0,
    height: 60,
    width: 60,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  modalTitleOfficeScrollY: {
    position: "absolute",
    top: 15,
    textAlign: "center",
    fontFamily: "Archivo_700Bold",
    fontSize: 20,
    color: colors.white,
    textTransform: "uppercase",
    zIndex: 1,
  },
  modalDescription: {
    width: width,
    padding: 10,
  },
  modalTitleDescription: {
    marginTop: -10,
    marginBottom: 10,
    fontFamily: "Archivo_700Bold",
    color: colors.regular,
    fontSize: fonts.bigger,
    paddingLeft: 15,
    textAlign: "center",
    textTransform: "uppercase",
  },
  modalTextDescription: {
    fontFamily: "Archivo_400Regular",
    color: colors.regular,
    fontSize: fonts.regular,
    paddingHorizontal: 10,
    textAlign: "center",
  },
  modalContentAmount: {
    alignItems: "center",
    justifyContent: "space-around",
    flexDirection: "row",
    width: width,
    paddingVertical: 10,
    marginBottom: 10,
  },
  modalControlAmount: {
    flexDirection: "row",
  },
  modalBtnSub: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.light,
    height: 43,
    width: 43,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
  },
  modalBtnAdd: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.light,
    height: 43,
    width: 43,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  modalAmount: {
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.big,
    backgroundColor: colors.light,
    height: 43,
    minWidth: 43,
    maxWidth: 100,
    marginHorizontal: 1,
    textAlignVertical: "center",
    textAlign: "center",
  },
  modalPrice: {
    position: "absolute",
    bottom: 20,
    width: "100%",
    zIndex: 1,
  },
  modalPriceNormal: {
    textAlign: "right",
    paddingRight: 15,
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.bigger,
    color: colors.darker,
  },
  modalTextPrice: {
    top: 8,
    textAlign: "right",
    paddingRight: 15,
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.small,
    color: colors.regular,
    zIndex: 1,
  },
  modalTextPricePromotion: {
    textAlign: "right",
    paddingRight: 15,
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.bigger,
    color: colors.red,
  },
  titleClose: {
    fontFamily: "Archivo_700Bold",
    color: colors.red,
    textAlign: "center",
    paddingBottom: 8,
  },
  modalTitleAdditional: {
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.big,
  },
  modalContentButton: {
    alignItems: "center",
    height: 100,
    padding: 20,
    marginBottom: 8,
  },
  textModalProduct: {
    fontSize: fonts.bigger,
  },
  groupText: {
    flexDirection: "row",
    alignItems: "center",
  },
  textValuePromotion: {
    fontSize: fonts.regular,
    fontWeight: "bold",
    color: colors.red,
  },
  groupAmount: {
    flexDirection: "row",
    paddingVertical: 15,
    alignItems: "center",
  },
  textAmout: {
    fontSize: 35,
    paddingHorizontal: 45,
  },

  buttonComprar: {
    flexDirection: "row",
    backgroundColor: colors.primary,
    height: 50,
    width: "90%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  buttonComprarDisabled: {
    flexDirection: "row",
    backgroundColor: colors.light,
    height: 50,
    width: "90%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    borderRadius: 8,
  },
  titleButtonComprar: {
    fontFamily: "Archivo_700Bold",
    color: colors.white,
    marginHorizontal: 10,
    textTransform: "uppercase",
  },

  priceContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 5,
    paddingLeft: 10,
    height: "25%",
  },
  imgProductPromotion: {
    position: "absolute",
    top: 0,
    left: -5,
    width: 180,
    height: 90,
    resizeMode: "contain",
  },
  input: {
    textAlignVertical: "top",
    backgroundColor: "#FFF",
    borderRadius: 4,
    marginHorizontal: 10,
    padding: 15,
    fontSize: fonts.regular,
    borderWidth: 1,
    borderColor: colors.light,
  },
});

export default styles;
