import { StyleSheet, Dimensions } from "react-native";
import { colors, fonts } from "../../Styles";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    position: "relative",
    backgroundColor: colors.white,
    borderRadius: 8,
    margin: 10,
    width: 150,
    height: 150,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    margin: 8,
    width: "100%",
    height: "100%",
    backgroundColor: colors.white,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  headerImage: {
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    height: 200,
    width: width,
  },
  close: {
    position: "absolute",
    top: 0,
    right: 0,
    height: 60,
    width: 60,
    justifyContent: "center",
    alignItems: "center",
  },
  imageModal: {
    marginTop: 10,
    width: width / 1.9,
    height: width / 1.9,
    resizeMode: "center",
  },
  modalImageBG: {
    position: "absolute",
    width: "75%",
    height: 55,
    resizeMode: "contain",
  },
  imageModalLeft: {
    position: "absolute",
    left: 15,
    top: -20,
    width: 150,
  },
  titleoffsetScrollY: {
    position: "absolute",
    top: 70,
    width: width - 160,
    right: 10,
    alignItems: "center",
  },
  modalTitleOfficeScrollY: {
    textAlign: "center",
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.big,
    color: colors.darker,
    marginBottom: 10,
  },
  modalDescription: {
    width: width,
    padding: 10,
  },
  modalTitleDescription: {
    marginTop: -10,
    marginBottom: 10,
    fontFamily: "Archivo_700Bold",
    color: colors.regular,
    fontSize: fonts.bigger,
    paddingLeft: 15,
    textAlign: "center",
    textTransform: "uppercase",
  },
  modalTextDescription: {
    fontFamily: "Poppins_400Regular",
    color: colors.regular,
    fontSize: fonts.smaller,
    paddingHorizontal: 28,
    textAlign: "justify",
  },
  modalContentAmount: {
    alignItems: "center",
    justifyContent: "space-around",
    flexDirection: "row",
    width: width,
    paddingVertical: 10,
    marginBottom: 10,
  },
  modalControlAmount: {
    flexDirection: "row",
  },
  modalBtnSub: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.light,
    height: 43,
    width: 43,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
  },
  modalBtnAdd: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.light,
    height: 43,
    width: 43,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  modalAmount: {
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.big,
    backgroundColor: colors.light,
    height: 43,
    minWidth: 43,
    maxWidth: 100,
    marginHorizontal: 1,
    textAlignVertical: "center",
    textAlign: "center",
  },
  modalPrice: {
    width: "100%",
  },
  modalPriceNormal: {
    textAlign: "right",
    paddingRight: 15,
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.bigger,
    color: colors.darker,
  },
  modalTextPrice: {
    top: 8,
    textAlign: "right",
    paddingRight: 15,
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.small,
    color: colors.darker,
    zIndex: 1,
  },
  modalTextPricePromotion: {
    textAlign: "right",
    paddingRight: 15,
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.bigger,
    color: colors.red,
  },
  contentAdditional: {
    backgroundColor: colors.lighter,
    width: width,
    paddingHorizontal: 20,
    paddingVertical: 5,
    borderBottomLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  modalTitleAdditional: {
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.big,
  },
  modalContentButton: {
    alignItems: "center",
    height: 100,
    padding: 20,
    marginBottom: 8,
  },
  textModalProduct: {
    fontSize: fonts.bigger,
  },
  groupText: {
    flexDirection: "row",
    alignItems: "center",
  },
  textValuePromotion: {
    fontSize: fonts.regular,
    fontWeight: "bold",
    color: colors.red,
  },
  groupAmount: {
    flexDirection: "row",
    paddingVertical: 15,
    alignItems: "center",
  },
  textAmout: {
    fontSize: 35,
    paddingHorizontal: 45,
  },
  textAlertProductCarts: {
    fontFamily: "Archivo_400Regular",
    fontSize: 16,
    paddingBottom: 20,
    color: colors.red,
    textAlign: "center",
    lineHeight: 20,
  },
  textAlert: {
    fontFamily: "Poppins_400Regular",
    fontSize: 12,
    textAlign: "center",
    color: colors.darker,
  },
  containerButtonAdd: {
    flexDirection: "row",
    justifyContent: "space-around",
    borderTopWidth: 2,
    borderTopColor: colors.lighter,
    width: "100%",
  },
  buttonComprar: {
    flexDirection: "row",
    backgroundColor: colors.primary,
    height: 50,
    width: "90%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  titleButtonComprar: {
    fontFamily: "Archivo_700Bold",
    color: colors.white,
    marginHorizontal: 10,
    textTransform: "uppercase",
  },
  buttonCancel: {
    backgroundColor: colors.light,
    height: 50,
    width: 130,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  titleButtonCancel: {
    fontFamily: "Archivo_700Bold",
    color: colors.darker,
  },
  buy: {
    opacity: 0.3,
  },
  textUnit: {
    position: "absolute",
    color: colors.red,
    padding: 2,
    left: 5,
    top: 5,
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.smaller,
    backgroundColor: "rgba(255,255,255,0.4)",
    borderRadius: 4,
    zIndex: 1,
  },
  imgContent: {
    backgroundColor: colors.primary,
    height: "55%",
  },
  description: {
    height: "22.5%",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 5,
    paddingTop: 5,
  },
  titleDescription: {
    fontFamily: "Archivo_700Bold",
    fontSize: fonts.smaller,
    color: colors.dark,
    textAlign: "center",
    textTransform: "uppercase",
  },
  priceContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 5,
    paddingLeft: 10,
    height: "22.5%",
  },
  imgProduct: {
    resizeMode: "cover",
    height: "100%",
    width: "100%",
  },
  imgProductPromotion: {
    position: "absolute",
    top: 0,
    left: -5,
    width: 160,
    height: 90,
    resizeMode: "contain",
    zIndex: 1,
  },
  textPrice: {
    fontFamily: "Archivo_700Bold",
    fontWeight: "bold",
    color: colors.darker,
  },
});

export default styles;
